name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang:
    runs-on: macos-latest

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Install autotools
      run: |
        brew update
        brew install automake autoconf libtool pkg-config
      
    - name: Clone Vapoursynth-Classic
      run: |
        git clone https://github.com/AmusementClub/vapoursynth-classic
        pushd vapoursynth-classic

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --branch v3.0 --depth 1
        pushd zimg
        ./autogen.sh
        ./configure
        make -j3
        sudo make install -j3
        popd
        rm -rf zimg

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.9

    - name: Install cython
      run: |
        python -m pip install --upgrade pip
        pip install cython

    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=$pythonLocation/lib/pkgconfig" >> $GITHUB_ENV

    - name: configure
      run: |
        ./autogen.sh
        # somehow newer macOS imagemagick requires -fopenmp to build?
        ./configure --disable-imwri

    - name: make
      run: make -j3

    - name: make install
      run: |
        sudo make install -j3
        pip install .

    - name: Finish install vapoursynth classic
      run: |
        popd
        rm -rf vapoursynth-classic
        
    - name: Install brew packages
      run: sh brew.sh

    - name: Copy files
      run: |
        sudo cp local-lib/* /usr/local/lib
        sudo cp vapoursynth-libs/* /usr/local/lib/vapoursynth

    - name: Test dylibs
      run: |
        sudo cp tools/checkdylib.py /usr/local/lib/vapoursynth
        cd /usr/local/lib/vapoursynth
        for file in .; do sudo python checkdylib.py $file; done;
