name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang:
    runs-on: macos-latest

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Install dependencies and vapoursynth
      run: |
        brew update
        brew install automake autoconf libtool pkg-config vapoursynth libx11 ffmpeg fftw xxhash fontconfig freetype gettext glib imagemagick libarchive libass liblqr little-cms2 llvm llvm@15 tesseract pipx vvenc zstd
        pip install git+https://github.com/HomeOfVapourSynthEvolution/mvsfunc
        
    - name: Copy files
      run: |
        sudo mkdir /usr/local/lib
        sudo mkdir /opt/homebrew/lib/vapoursynth
        sudo cp local-lib/* /usr/local/lib
        sudo cp vapoursynth-libs/* /opt/homebrew/lib/vapoursynth
        sudo cp tools/checkdylib.py /opt/homebrew/lib/vapoursynth

    - name: Test vspipe
      run: |
        cd test
        vspipe example.vpy /dev/null

    - name: Test dylibs
      run: |
        cd /opt/homebrew/lib/vapoursynth
        ls
        for file in *; do sudo python checkdylib.py $file; done;

