name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang:
    runs-on: macos-latest

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Install autotools and vapoursynth
      run: |
        brew update
        brew install automake autoconf libtool pkg-config vapoursynth
        
    - name: Install brew packages
      run: sh brew.sh

    - name: Copy files
      run: |
        sudo mkdir /usr/local/lib
        sudo mkdir /usr/local/lib/vapoursynth
        sudo cp local-lib/* /usr/local/lib
        sudo cp vapoursynth-libs/* /usr/local/lib/vapoursynth

    - name: Test dylibs
      run: |
        sudo cp tools/checkdylib.py /usr/local/lib/vapoursynth
        cd /usr/local/lib/vapoursynth
        for file in .; do sudo python checkdylib.py $file; done;
