name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  install_and_test:
    runs-on: macos-latest

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.5
    - run: |
        python -m site
        whereis python

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Install dependencies and vapoursynth
      env:
        PYTHONPATH: /Users/runner/hostedtoolcache/Python/3.12.5/arm64/lib/site-packages
      run: |
        brew update
        sh brew.sh
        export LIBRARY_PATH=/opt/homebrew/lib/:$LIBRARY_PATH
        export LD_LIBRARY_PATH=/opt/homebrew/lib/:$LD_LIBRARY_PATH
        export PYTHONAPATH=/Users/runner/hostedtoolcache/Python/3.12.5/arm64/lib/site-packages

    - name: Copy files
      run: |
        sudo mkdir /usr/local/lib
        sudo mkdir /opt/homebrew/lib/vapoursynth
        sudo cp local-lib/* /usr/local/lib
        sudo cp vapoursynth-libs/* /opt/homebrew/lib/vapoursynth
        sudo cp tools/checkdylib.py /opt/homebrew/lib/vapoursynth

    # - name: Test vspipe
    #   run: |
    #     cd test
    #     vspipe test1.vpy /dev/null
    
    # - name: Test production
    #   env:
    #     PYTHONPATH: /Users/runner/hostedtoolcache/Python/3.12.5/arm64/lib/site-packages
    #   run: |
    #     export PYTHONAPATH=/Users/runner/hostedtoolcache/Python/3.12.5/arm64/lib/site-packages
    #     cd test
    #     python -m site
    #     pip show mvsfunc
    #     vspipe -c y4m test2.vpy - | ffmpeg -i - -c:v libx265 -crf 15 -preset slow output1.mkv    

    - name: Test dylibs
      run: |
        cd /opt/homebrew/lib/vapoursynth
        ignore=("libbm3dcpu.dylib"); for file in *.dylib; do [[ ! " ${ignore[@]} " =~ " $file " ]] && echo "$file" && sudo python checkdylib.py "$file"; done
